### ISSUE TITLE
[iOS] Security policy prohibits use of Assistant

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardAssistant#222]
Assistant doesn't start on https://www.pinterest.de/pin/631981760181706193/ due to site's security police. Please check, if we can do something to circumvent.

https://github.com/AdguardTeam/AdguardFilters/issues/15709

**Comment by ameshkov** [comment]
This is a known issue with the iOS version of Assistant and there's nothing we can do with it :(

iOS does not provide a way to suppress or modify websites' content security policies from within an extension, that's why we have to just show this ugly warning when injecting the Assistant code is prohibited.

**Comment by BlazDT** [comment]
Thanks for the info. So again a restriction :(
