### ISSUE TITLE
Adguard Browser Assistant Extension in Firfox not working in Nightly build of Adguard Windows

### ISSUE THREAD

**Issue by Batman2814** [AdguardTeam/AdguardAssistant#397]
Adguard browser Assistant extension not working in firefox when I have the Nightly build of Adguard for Windows installed. When I went back to stable Adguard for Windows it was working fine so if you can fix this in the next nightly build of Adguard for Windows which I'm back on the NIghtly currently I'll be waiting.

**Comment by Aydinv13** [comment]
@Batman2814 Hi there! 
Do you mean this one? 
<details>
  <summary>Screenshot </summary>

![screenshot](https://user-images.githubusercontent.com/73467237/229462684-9621fa2d-880e-4772-9045-a7147a345600.png)
</details>

**Comment by Batman2814** [comment]
here's some screenshots
![20230403_07421291_Edited](https://user-images.githubusercontent.com/96619913/229514223-e29e395a-2c59-46aa-8c0b-b7c7ef99479a.png)
![20230403_07435743_Edited](https://user-images.githubusercontent.com/96619913/229514228-5d2be53a-e4a7-40f0-943f-03c14672ee59.png)
![20230403_07455182_Edited](https://user-images.githubusercontent.com/96619913/229514233-2f387bf7-9a08-47b0-be55-5e1ecb031b77.png)

**Comment by Aydinv13** [comment]
@Batman2814 

1. Does this occur only with Firefox?
2. Does the app itself work at that moment?
3. Are there any applications or extensions installed that affect traffic?
4. What if you turn off AdGuard Browser Extension?
5. Could you please check if the problem is solved with the latest [nightly](https://agrd.io/windows_nightly) build?

**Comment by Aydinv13** [comment]
@Batman2814 

If the latest doesn't help please grab the debug logs:
1. Collect the debug log as it's [explained here](https://kb.adguard.com/en/windows/solving-problems/adguard-logs).
2. Remember the exact time when the issue was reproduced. We will need it to find the corresponding records in the log file.
3. Send the archive to `devteam@adguard.com` and mention this issue number in the subject.

**Comment by Batman2814** [comment]
Logs have been sent

**Comment by Aydinv13** [comment]
Could you please also answer here https://github.com/AdguardTeam/AdguardAssistant/issues/397#issuecomment-1497127777

**Comment by Batman2814** [comment]
The reproduced time was at 6:53am and 6:54am.

 

It was happening on Adguard for Windows Stable version also and on Nightly.

 

Seems to be happening only in firefox. Works fine on Microsoft Edge browser.

**Comment by Aydinv13** [comment]
Could you please check if the problem is solved with [this](https://agrd.io/windows_nightly) build? We also need your logs in case the issue reproduces (as I mentioned here https://github.com/AdguardTeam/AdguardAssistant/issues/397#issuecomment-1497147478). Thank you.

**Comment by Aydinv13** [comment]
In addition please reinstall Browser Assistant for Firefox. Does this help?

**Comment by Batman2814** [comment]
I have already sent you guys the logs.

**Comment by Batman2814** [comment]
sent logs again just now.

**Comment by Batman2814** [comment]
seems to be fixed in Firefox version 112 which was released today
